rolex: Initial Anykernel3

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -10,7 +10,6 @@ $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMO
 
 $BOOTMODE && DIR=/sdcard || DIR=$(dirname "$ZIPFILE");
 
-test "$ANDROID_ROOT" || ANDROID_ROOT=/system;
 test "$home" || home=/tmp/anykernel;
 
 ui_print() {
@@ -18,11 +17,6 @@ ui_print() {
     echo -e "ui_print $1\nui_print" > $OUTFD;
     shift;
   done;
-}
-ui_printfile() {
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < $1;
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
 file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
@@ -42,49 +36,29 @@ cleanup() {
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print " " "Creating debugging archive in $DIR...";
+      ui_print " " "- Creating debugging archive in $DIR...";
       test -f /tmp/recovery.log && log=/tmp/recovery.log;
       $bb tar -czf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $home $log;
     ;;
   esac;
 }
-setup_mountpoint() {
-  test -L $1 && $bb mv -f $1 ${1}_link;
-  if [ ! -d $1 ]; then
-    rm -f $1;
-    mkdir $1;
-  fi;
-}
 is_mounted() { $bb mount | $bb grep -q " $1 "; }
-umount_all() {
+unmount_all() {
   ($bb umount /system;
-  $bb umount -l /system;
-  if [ -e /system_root ]; then
+  if [ -d /system_root -a ! -f /system/build.prop ]; then
     $bb umount /system_root;
-    $bb umount -l /system_root;
   fi;
+  $bb umount /system;
   umount /vendor;
-  umount -l /vendor;
-  if [ "$umount_data" ]; then
-    $bb umount /data;
-    $bb umount -l /data;
-  fi) 2>/dev/null;
-}
-restore_env() {
-  test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
-  test "$savedpre" && export LD_PRELOAD="$savedpre";
-  umount_all;
-  ($bb mv -f /system_link /system;
-  $bb mv -f /system_root_link /system_root;
-  $bb umount -l /dev/random) 2>/dev/null;
+  $bb umount /data) 2>/dev/null;
 }
 abort() {
-  ui_print "$@";
+  ui_print "$*";
   debugging;
-  restore_env;
   if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
+  unmount_all;
   exit 1;
 }
 
@@ -95,7 +69,7 @@ mkdir -p $home/bin;
 cd $home;
 unzip -o "$ZIPFILE";
 if [ $? != 0 -o ! "$(ls tools)" ]; then
-  abort "Unzip failed. Aborting...";
+  abort "- Unzip failed. Aborting...";
 fi;
 for arch32 in x86 arm; do
   if [ -d $home/tools/$arch32 ]; then
@@ -113,51 +87,43 @@ chmod 755 $bb;
 $bb chmod -R 755 tools bin;
 $bb --install -s bin;
 if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "Busybox setup failed. Aborting...";
+  abort "- Busybox setup failed. Aborting...";
 fi;
 
 if [ -f banner ]; then
-  ui_printfile banner;
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < banner;
   ui_print " " " ";
 fi;
 
-ui_print "$(file_getprop anykernel.sh kernel.string)";
+ui_print "****************************************";
+ui_print "* $(file_getprop anykernel.sh kernel.string)";
+ui_print "* For Xiaomi Redmi 4A ";
+ui_print "* By Muhammad Fadlyas (@Mmhmdfas) ";
+ui_print "****************************************";
 if [ -f version ]; then
   ui_print " ";
-  ui_printfile version;
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < version;
   ui_print " ";
 fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
-
-$BOOTMODE || $bb mount -o bind /dev/urandom /dev/random;
-umount_all;
-setup_mountpoint $ANDROID_ROOT;
-if ! is_mounted $ANDROID_ROOT; then
-  $bb mount -o ro -t auto $ANDROID_ROOT;
+ui_print "- Checking Image";
+ui_print "- Founded Image ";
+unmount_all;
+if ! is_mounted /system; then
+  $bb mount -o ro -t auto /system;
 fi;
-case $ANDROID_ROOT in
-  /system_root) setup_mountpoint /system;;
-  /system)
-    if [ -f /system/system/build.prop ]; then
-      setup_mountpoint /system_root;
-      $bb mount --move /system /system_root;
-      if [ $? != 0 ]; then
-        $bb umount /system;
-        $bb umount -l /system 2>/dev/null;
-        $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
-      fi;
-    fi;
-  ;;
-esac;
-if is_mounted /system_root; then
+($bb mount -o ro -t auto /vendor;
+$bb mount /data) 2>/dev/null;
+if [ -f /system/system/build.prop ]; then
+  $bb umount /system;
+  ($bb umount /system;
+  mkdir /system_root) 2>/dev/null;
+  $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
   $bb mount -o bind /system_root/system /system;
 fi;
-$bb mount -o ro -t auto /vendor 2>/dev/null;
-if ! is_mounted /data; then
-  $bb mount /data;
-  umount_data=1;
-fi;
-
 savedpath="$LD_LIBRARY_PATH";
 savedpre="$LD_PRELOAD";
 unset LD_LIBRARY_PATH;
@@ -176,24 +142,24 @@ elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.pro
 fi;
 
 if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
+  ui_print "- Checking device";
   device=$(getprop ro.product.device);
   product=$(getprop ro.build.product);
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
-      ui_print "$testname" " ";
+      ui_print "- Device Codename: $testname";
       match=1;
       break;
     fi;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "- Unsupported device. Aborting...";
   fi;
 fi;
 
 supported_ver=$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]');
 if [ "$supported_ver" ]; then
-  ui_print "Checking Android version...";
+  ui_print "- Checking Android Version";
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
   if echo $supported_ver | $bb grep -q '-'; then
@@ -211,15 +177,15 @@ if [ "$supported_ver" ]; then
     done;
   fi;
   if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
+    ui_print "- Android Version: $android_ver";
   else
-    abort " " "Unsupported Android version. Aborting...";
+    abort "- Unsupported Android version. Aborting...";
   fi;
 fi;
 
 supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $bb grep -oE '[0-9]{4}-[0-9]{2}|-');
 if [ "$supported_lvl" ]; then
-  ui_print "Checking Android security patch level...";
+  ui_print "- Checking Android security patch level...";
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | $bb grep -oE '[0-9]{4}-[0-9]{2}');
   if echo $supported_lvl | $bb grep -q '^\-'; then
@@ -233,13 +199,17 @@ if [ "$supported_lvl" ]; then
     hi_lvl=9999-99;
   fi;
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $bb sort -g | $bb grep -n "$parsed_lvl" | $bb grep -q '^2:'; then
-    ui_print "$android_lvl" " ";
+    ui_print "- Android security patch: $android_lvl";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort "- Unsupported Android security patch level. Aborting...";
   fi;
 fi;
 
-ui_print "Installing...";
+ui_print "- Backuping Boot.img";
+sleep 1
+ui_print "- Unpacking Boot.img";
+sleep 1
+ui_print "- Patching Boot.img";
 core=$($bb grep -oE 'ak.*core.sh' anykernel.sh);
 test -f tools/$core || $bb ln -s $home/tools/ak*-core.sh $home/tools/$core;
 PATH="$home/bin:$PATH" home=$home $bb ash anykernel.sh $2;
@@ -248,7 +218,7 @@ if [ $? != 0 ]; then
 fi;
 
 if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
-  ui_print " " "Pushing modules...";
+  ui_print "- Pushing modules";
   $bb mount -o rw,remount -t auto /system;
   $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
   cd $home/modules;
@@ -280,10 +250,23 @@ if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
 fi;
 
 debugging;
-restore_env;
 
 if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " " " "Done!";
+test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
+test "$savedpre" && export LD_PRELOAD="$savedpre";
+
+ui_print "- Repacking Boot.img";
+sleep 1
+ui_print "- Flashing Boot.img";
+sleep 2
+ui_print "- Unmount partitions";
+sleep 1
+
+unmount_all;
+
+ui_print "**************************************************";
+ui_print "                       Enjoy                      ";
+ui_print "**************************************************";
